# variables are read from .env

services:
  app:
    image: tomjtoth/saldo
    build:
      context: .
      tags:
        - tomjtoth/saldo
    volumes:
      - ./data:/app/data
      - ./.env.local:/app/.env
    ports:
      - 127.0.0.1:3000:3000
    restart: unless-stopped
