POST http://localhost:3000/api/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzMxODUxNzEyfQ.A1gV9F3wTyH5OWZxWxIQemErCeeG805DhR_n8qesDz0
content-type: application/json

{"entities":[

    {
        "name": "tomjtoth",
        "email": "tomjtoth@gmail.com2",
        "password": "qqqqqqqq"
    }
]}


### log in to existing user

POST http://localhost:3000/login
content-type: application/json

{
        "email": "tomjtoth@gmail.com2",
        "password": "qqqqqqqq"
    
}


###

DELETE http://localhost:3000/api/categories
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzMxODUxNzEyfQ.A1gV9F3wTyH5OWZxWxIQemErCeeG805DhR_n8qesDz0


### update categories

PUT http://localhost:3000/api/categories
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzMxODUxNzEyfQ.A1gV9F3wTyH5OWZxWxIQemErCeeG805DhR_n8qesDz0
content-type: application/json

{"entities":[
    {
        "id": 3,
        "category": "33333",
        "status_id": 11
    },
    {
        "id": 4,
        "category": "44444",
        "status_id": 22
    }
]}

###

PUT http://localhost:3000/api/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzMxODUxNzEyfQ.A1gV9F3wTyH5OWZxWxIQemErCeeG805DhR_n8qesDz0
content-type: application/json

{"entities":[
{
    "id": 0 ,
    "status_id": 2,
    "name": "Tamás"
}
]}
