POST http://localhost:3000/api/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNzMxOTEwODk0fQ.23TO7D0c385lmTJeHCNM8Q7cOF1kEsUbXDc21vduBeQ
content-type: application/json

{"entities":[

    {
        "name": "tomjtoth",
        "email": "tomjtoth@gmail.com2",
        "password": "qqqqqqqq"
    }
]}


### log in to existing user

POST http://localhost:3000/login
content-type: application/json

{
        "email": "tomjtoth@gmail.com",
        "password": "qwer1234"
    
}


###

DELETE http://localhost:3000/api/categories
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNzMxOTEwODk0fQ.23TO7D0c385lmTJeHCNM8Q7cOF1kEsUbXDc21vduBeQ


### update categories

PUT http://localhost:3000/api/categories
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNzMxOTEwODk0fQ.23TO7D0c385lmTJeHCNM8Q7cOF1kEsUbXDc21vduBeQ
content-type: application/json

{"entities":[
    {
        "id": 3,
        "category": "33333",
        "status_id": 11
    },
    {
        "id": 4,
        "category": "44444",
        "status_id": 22
    }
]}

###

PUT http://localhost:3000/api/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiaWF0IjoxNzMxOTEwODk0fQ.23TO7D0c385lmTJeHCNM8Q7cOF1kEsUbXDc21vduBeQ
content-type: application/json

{"entities":[
{
    "id": 1 ,
    "status_id": 0,
    "name": "Hanna",
    "passwd": "qwer1234",
    "email": "joku@muu.fi"
}
]}
