PUT http://localhost:3000/api/users
content-type: application/json

{"entities":[

    {
        "id":6,
        "status_id": 0,
        "name": "test3.2",
        "email": "asdf@asd11f.com",
        "password": "asdsadsadsa"
    },
    { "id":7,
        "status_id": 0,
        "name": "test6.2",
        "email": "asdf@asdf3322.com",
        "password": "trewtfdsggfgfgf"
    }
]}


###

DELETE http://localhost:3000/api/categories


###

PUT http://localhost:3000/api/categories
content-type: application/json

{"entities":[
    {
        "id": 3,
        "category": "asd33",
        "status_id": 5
    },
    {
        "id": 4,
        "category": "asd44",
        "status_id": 0
    }
]}

###

PUT http://localhost:3000/api/users
content-type: application/json

{"entities":[
{
    "id": 0 ,
    "status_id": 2,
    "name": "Tamás"
}
]}
