name: Run tests and upload coverage

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose Services
        run: |
          docker-compose -f docker-compose.dev.yml up -d
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSERNAME: ${{ secrets.PGUSERNAME }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}

      - run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec $(docker ps -qf "name=postgres-test") pg_isready -U ${PGUSERNAME}; do
            echo "Waiting for PostgreSQL to start..."
            sleep 1
          done
        env:
          PGUSERNAME: ${{ secrets.PGUSERNAME }}

      - run: npm run coverage
        env:
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSERNAME: ${{ secrets.PGUSERNAME }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Merge dev into main
      #   if: success()
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git fetch --all
      #     git checkout main
      #     git merge --allow-unrelated-histories dev
      #     git push origin main
